# Generated by Django 3.1 on 2020-09-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('email_id', models.CharField(max_length=256)),
                ('phone_num', models.CharField(max_length=16)),
                ('employee_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('employee_address', models.TextField()),
                ('date_f_birth', models.DateField()),
                ('employee_job', models.ManyToManyField(blank=1, to='myapi.AvailableJobs')),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
